#!/bin/bash

# VARS ========================================================================
local COMMIT_MSG_FILE=$1
local COMMIT_SOURCE=$2
local SHA1=$3

# IMP =========================================================================
# Put brach name at start of the line 
function formatCommitMessage {
  hint=$(cat "$COMMIT_MSG_FILE")
  ticket="${BASH_REMATCH[1]}"
  echo "${ticket} " > "$COMMIT_MSG_FILE"
  echo "$hint" >> "$COMMIT_MSG_FILE"
}

if [[ -z "$COMMIT_SOURCE" ]]
  then
    local ref=$(git rev-parse --abbrev-ref HEAD)
  if [[ $ref =~ ^.*((BR|FRNT|GUESSWHOZ-GIT-GURU)-[0-9]+).* ]]
    then 
    formatCommitMessage
  fi
fi


